class LangConverter {
  List<String> english = [
    'Meningitis (Meningococcal disease)',
    'Tick-borne Encephalitis',
    'Japanese Encephalitis',
    'Polio',
    'COVID-19',
    'Hepatitis A',
    'Rabies',
    'Hepatitis B',
    'Yellow Fever',
    'Cholera',
    'Typhoid',
    'Measles',
    'Routine vaccines',
    'Chikungunya',
    'Malaria'
  ];
  List<String> german = [
    "COVID-19",
    "Denguefieber",
    "Diphtherie",
    "Ebola",
    "FSME",
    "Gelbfieber",
    "Gürtelrose",
    "Haemophilus Influenzae-Typ-B",
    "Hepatitis-A",
    "Hepatitis-B",
    "HPV",
    "Influenza",
    "Japanische Enzephalitis",
    "Masern",
    "Meningokokken",
    "Milzbrand (Anthrax)",
    "Mumps",
    "Pertussis (Keuchhusten)",
    "Pneumokokken",
    "Pocken",
    "Poliomyelitis (Kinderlähmung)",
    "Röteln",
    "Rotavirus",
    "RSV",
    "Tetanus (Wundstarrkrampf)",
    "Tollwut",
    "Typhus",
    "Varizellen (Windpocken)"
  ];

  static final Map<String, String> diseaseTranslation = {
    "COVID-19": "COVID-19",
    "Dengue Fever": "Denguefieber",
    "Diphtheria": "Diphtherie",
    "Ebola": "Ebola",
    "Tick-borne Encephalitis": "FSME",
    "Yellow Fever": "Gelbfieber",
    "Shingles": "Gürtelrose",
    "Haemophilus Influenzae Type B": "Haemophilus Influenzae-Typ-B",
    "Hepatitis A": "Hepatitis-A",
    "Hepatitis B": "Hepatitis-B",
    "HPV": "HPV",
    "Influenza": "Influenza",
    "Japanese Encephalitis": "Japanische Enzephalitis",
    "Measles": "Masern",
    "Meningitis (Meningococcal disease)": "Meningokokken",
    "Anthrax": "Milzbrand (Anthrax)",
    "Mumps": "Mumps",
    "Pertussis (Whooping Cough)": "Pertussis (Keuchhusten)",
    "Pneumococcal": "Pneumokokken",
    "Smallpox": "Pocken",
    "Polio": "Poliomyelitis (Kinderlähmung)",
    "Rubella": "Röteln",
    "Rotavirus": "Rotavirus",
    "RSV": "RSV",
    "Tetanus": "Tetanus (Wundstarrkrampf)",
    "Rabies": "Tollwut",
    "Typhoid": "Typhus",
    "Chickenpox (Varicella)": "Varizellen (Windpocken)"
  };

}
