class LangConverter {
  List<String> english = [
    "COVID-19",
    "Dengue Fever",
    "Diphtheria",
    "Ebola",
    "Tick-borne Encephalitis",
    "Yellow Fever",
    "Shingles",
    "Haemophilus Influenzae Type B",
    "Hepatitis A",
    "Hepatitis B",
    "HPV",
    "Influenza",
    "Japanese Encephalitis",
    "Measles",
    "Meningitis (Meningococcal disease)",
    "Anthrax",
    "Mumps",
    "Pertussis (Whooping Cough)",
    "Pneumococcal",
    "Smallpox",
    "Polio",
    "Rubella",
    "Rotavirus",
    "RSV",
    "Tetanus",
    "Rabies",
    "Typhoid",
    "Chickenpox (Varicella)",
    "Cholera",
    "Malaria",
    "Chikungunya"
  ];

  List<String> german = [
    "COVID-19",
    "Denguefieber",
    "Diphtherie",
    "Ebola",
    "FSME",
    "Gelbfieber",
    "Gürtelrose",
    "Haemophilus Influenzae-Typ-B",
    "Hepatitis-A",
    "Hepatitis-B",
    "HPV",
    "Influenza",
    "Japanische Enzephalitis",
    "Masern",
    "Meningokokken",
    "Milzbrand (Anthrax)",
    "Mumps",
    "Pertussis (Keuchhusten)",
    "Pneumokokken",
    "Pocken",
    "Poliomyelitis (Kinderlähmung)",
    "Röteln",
    "Rotavirus",
    "RSV",
    "Tetanus (Wundstarrkrampf)",
    "Tollwut",
    "Typhus",
    "Varizellen (Windpocken)",
    "Cholera",
    "Malaria",
    "Chikungunya"
  ];

  static final Map<String, String> diseaseTranslation = {
    "COVID-19": "COVID-19",
    "Dengue Fever": "Denguefieber",
    "Diphtheria": "Diphtherie",
    "Ebola": "Ebola",
    "Tick-borne Encephalitis": "FSME",
    "Yellow Fever": "Gelbfieber",
    "Shingles": "Gürtelrose",
    "Haemophilus Influenzae Type B": "Haemophilus Influenzae-Typ-B",
    "Hepatitis A": "Hepatitis-A",
    "Hepatitis B": "Hepatitis-B",
    "HPV": "HPV",
    "Influenza": "Influenza",
    "Japanese Encephalitis": "Japanische Enzephalitis",
    "Measles": "Masern",
    "Meningitis (Meningococcal disease)": "Meningokokken",
    "Anthrax": "Milzbrand (Anthrax)",
    "Mumps": "Mumps",
    "Pertussis (Whooping Cough)": "Pertussis (Keuchhusten)",
    "Pneumococcal": "Pneumokokken",
    "Smallpox": "Pocken",
    "Polio": "Poliomyelitis (Kinderlähmung)",
    "Rubella": "Röteln",
    "Rotavirus": "Rotavirus",
    "RSV": "RSV",
    "Tetanus": "Tetanus (Wundstarrkrampf)",
    "Rabies": "Tollwut",
    "Typhoid": "Typhus",
    "Chickenpox (Varicella)": "Varizellen (Windpocken)",
    "Cholera": "Cholera",
    "Malaria": "Malaria",
    "Chikungunya": "Chikungunya"
  };
}
